# Generated by Django 5.2.17 on 2026-09-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academy.placementresult')),
            ],
        ),
    ]
